### ISSUE TITLE
Cannot combine AS3/DO/TS in one play

### ISSUE THREAD

**Issue by boeboe** [f5devcentral/ansible-role-f5_atc_deploy_declaration#21]
**Problem description**

You cannot combine DO / AS3 / TS scenario's in one Playbook containing separate roles for the 3 ATC components. Once you have run this Galaxy rol for DO (ad an example), it will think all following actions are also for DO, even if they are for AS3 and TS used in different roles in the same playbook.

The reason is the following taks:

https://github.com/f5devcentral/ansible-role-f5_atc_deploy_declaration/blob/e8447de007f3ec0e0de26a9ce95f9dd614e64fff/tasks/main.yaml#L20

`atc_service` is defined already and not refreshed. 

**Workaround**

Pass the var yourself as described in the README.md, but no auto-detection is happening.

**Comment by focrensh** [comment]
If you specify the atc_service in the role, then it will avoid this. This happens from the role setting the var itself on the initial run.

```

    declarations:
      - name: Device
        file: do
      - name: Telemetry
        file: ts
      - name: AS3
        file: as3


    - name: ATC
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_service: "{{ item.name }}"
        atc_declaration: "{{ lookup('file', 'bigip/' + item.file + '.json') }}"
        atc_delay: 10
        atc_retries: 45
      loop: "{{ declarations }}"
```
